name: CI
on: [push]
jobs:
  do-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - run: make check-fmt
      - run: make start-db
      - run: make test